"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { supabase } from "@/lib/supabase";

const LOCK_KEY="sira-web-login-lock";
export default function AuthPage(){
 const router=useRouter(); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
 async function login(e:React.FormEvent){e.preventDefault();setMessage(""); const now=Date.now(); let lock={attempts:0,lockedUntil:0}; try{lock=JSON.parse(localStorage.getItem(LOCK_KEY)||"{}") as any}catch{}; if(lock.lockedUntil>now){setMessage(`Too many failed attempts. Try again in ${Math.ceil((lock.lockedUntil-now)/60000)} minute(s).`);return;} setBusy(true); const {error}=await supabase.auth.signInWithPassword({email:email.trim().toLowerCase(),password}); setBusy(false); if(error){const attempts=(lock.attempts||0)+1; const lockedUntil=attempts>=5?Date.now()+15*60*1000:0; localStorage.setItem(LOCK_KEY,JSON.stringify({attempts,lockedUntil})); setMessage(lockedUntil?"Login temporarily locked for 15 minutes.":`Invalid email or password. ${5-attempts} attempt(s) remaining.`);return;} localStorage.removeItem(LOCK_KEY); router.replace("/incidents");}
 return <div className="auth-page"><div className="auth-visual"><div className="auth-brand"><h1>SIRA</h1><p>Secure field incident monitoring, workflow tracking and geospatial reporting.</p></div></div><div className="auth-form-wrap"><form className="auth-form" onSubmit={login}><img className="auth-logo" src="/sira-icon.png" alt="SIRA"/><h2>Secure Login</h2><p>Use your registered email address and password.</p>{message&&<div className="notice error" style={{marginBottom:14}}>{message}</div>}<div className="field"><label>Email address</label><input className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email"/></div><div className="field"><label>Password</label><input className="input" type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/></div><button className="btn primary" style={{width:"100%",marginTop:8}} disabled={busy}>{busy?"Signing in…":"Sign in"}</button><p className="small" style={{textAlign:"center",marginTop:18}}>Need an account? <Link href="/signup" style={{color:"#1267e8",fontWeight:900}}>Create account</Link></p></form></div></div>;
}
